dp8/urls.py
from django.contrib import admin
from django.urls import path,include
import dp8app
from dp8app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',views.base,name="base"),
    path('',views.home,name="home"),
    path('dp8app/',include("dp8app.urls")),    
]

dp8app/urls.py
from django.urls import path
from dp8app import views

app_name="dp8app"


urlpatterns=[
    path('trial/',views.trial,name="trial"),
    path('profile/',views.profile,name="profile"),
]

dp8app/models.py
from django.db import models

# Create your models here.

dp8app/views.py
from django.shortcuts import render
from django.http import HttpResponse

def trial(request):
    return HttpResponse('<h1>Project is on air</h1>')

def base(request):
    return render(request,'base.html')

def home(request):
    return render(request,"dp8app/home.html")

def profile(request):
    name="pavan abhilash"
    return render(request,"dp8app/profile.html",{'name':name})
# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>base.html</title>
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>
    {% include "partials/_topbar.html" %}
    {% include "partials/_navbar.html" %}
    {% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>welcome to base page</h1>
        </div>
    </div>
    {% endblock %}
    {% include "partials/_footbar.html" %}
</body>
</html>

templates/dp8app/home.html
{% extends "base.html" %}

{% block title %}
<title>home.html</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>welcome to home page</h1>
    </div>
</div>
{% endblock %}

templates/dp8app/profile.html
{% extends "base.html" %}

{% block title %}
<title>profile.html</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Welcome to  profile page {{name}}</h1>
    </div>
</div>
{% endblock %}

templates/partials/_footbar.html
<div class="alert alert-primary" role="alert">
    <center>footer</center> 
</div>

templates/partials/_navbar.html
<div class="container">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dp8app:profile' %}">profile</a>
      </li>
    </ul>
</div>

templates/partials/_topbar.html
<div class="alert alert-secondary" role="alert">
    <center>Top Bar</center> 
</div>